name: Azure Web App CI/CD

on:
  push:
    branches:
      - heimdalltesting  # Replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Replace with the Java version you are using (e.g., '11' or '17')

    - name: Build with Maven
      run: mvn clean package  # Replace with your Maven build command

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'heimdall-core'  # Replace with your Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Add this secret to your GitHub repository with the Azure Web App publish profile content

az webapp deployment source config --name "MyFisrtWebAppName" --resource-group "MyFisrtWebAppName_group" --branch master --manual-integration --repo-url "https://github.com/pavanreddy255/pavanreddy255" --app-working-dir "/opt/java/openjdk"
