name: Deploy to Azure Web App

on:
  push:
    branches:
      - heimdalltesting  # Replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Replace with the Java version you are using

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'heimdall-core'  # Replace with your Azure Web App name
        #slot-name: 'production'  # Replace with the deployment slot name if using slots
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Add this secret to your GitHub repository with the Azure Web App publish profile content
        package: '$(Build.ArtifactStagingDirectory)/*.jar'
        # Change the package path if your Maven build output path is different

    - name: Install Azure CLI
      uses: azure/CLI@v1

    - name: Configure Azure Web App for Java
      run: |
        az webapp config set -n heimdall-webapp -g MyResourceGroup --java-version 11
        # Replace 'MyResourceGroup' with your actual Azure resource group name

    # Add more steps if required, such as setting up environment variables and configuring databases
